# RunTests.cmake
cmake_minimum_required(VERSION 3.11)

if(NOT CHOCTOOBJ)
    set(CHOCTOOBJ "./ChocToObj")
endif()
if(NOT PYTHON_EXECUTABLE)
    set(PYTHON_EXECUTABLE "python3")
endif()

if(FORTIFY_FAILURE_TEST)
    set(TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/ChocToObj-fortify-test")
else()
    set(TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/ChocToObj-test")
endif()
set(ISO "${TEST_DIR}/Flight_Simulator_Games_Collection.iso")
set(REFERENCE_ARCHIVE "${TEST_DIR}/chocmesh.zip")
set(DATA_DIR "${TEST_DIR}/data")
set(REFERENCE_DIR "${TEST_DIR}/reference")
set(OUTPUT_DIR "${TEST_DIR}/output")
file(MAKE_DIRECTORY "${TEST_DIR}" "${DATA_DIR}" "${REFERENCE_DIR}"
    "${OUTPUT_DIR}")

message(STATUS "Downloading the APDL Flight Simulator Games Collection...")
file(DOWNLOAD
    "https://archive.org/download/flight-simulator-games-collection/Flight_Simulator_Games_Collection.iso"
    "${ISO}"
    EXPECTED_HASH
        SHA256=4bc7c5b9f977f7a21ff02410c920492624304bfcc228bafac44d1417fb64c50d
    STATUS download_status
    SHOW_PROGRESS
    TIMEOUT 120
)
list(GET download_status 0 download_result)
list(GET download_status 1 download_error)
if(NOT download_result EQUAL 0)
    message(FATAL_ERROR "Failed to download game data: ${download_error}")
endif()

message(STATUS "Extracting Chocks Away data from the ISO image...")
execute_process(
    COMMAND "${PYTHON_EXECUTABLE}"
        "${CMAKE_CURRENT_LIST_DIR}/tests/ExtractChocksISO.py"
        "${ISO}" "${DATA_DIR}"
    RESULT_VARIABLE extract_result
)
if(NOT extract_result EQUAL 0)
    message(FATAL_ERROR "Failed to extract Chocks Away data")
endif()

message(STATUS "Downloading the published Chocks Away object meshes...")
file(DOWNLOAD
    "http://www.starfighter.acornarcade.com/mysite/download/chocmesh.zip"
    "${REFERENCE_ARCHIVE}"
    EXPECTED_HASH
        SHA256=9c7c5f5029e8f821f89cd5ef3f98c7cfa64d7e8571813b6e931a59473d24029f
    STATUS reference_download_status
    SHOW_PROGRESS
    TIMEOUT 60
)
list(GET reference_download_status 0 reference_download_result)
list(GET reference_download_status 1 reference_download_error)
if(NOT reference_download_result EQUAL 0)
    message(FATAL_ERROR
        "Failed to download reference data: ${reference_download_error}")
endif()
execute_process(
    COMMAND "${CMAKE_COMMAND}" -E tar xvf "${REFERENCE_ARCHIVE}"
    WORKING_DIRECTORY "${REFERENCE_DIR}"
    RESULT_VARIABLE reference_extract_result
    OUTPUT_QUIET
)
if(NOT reference_extract_result EQUAL 0)
    message(FATAL_ERROR "Failed to extract reference data")
endif()

set(LAND "${DATA_DIR}/Land")
set(OBJ3D "${DATA_DIR}/Obj3D")
set(EXTRA_DIR "${DATA_DIR}/Extra")

function(body_hash file result_name)
    if(NOT EXISTS "${file}")
        message(FATAL_ERROR "${file} was not created")
    endif()
    file(READ "${file}" contents)
    string(REPLACE "\r\n" "\n" contents "${contents}")
    foreach(header_line RANGE 1 2)
        string(FIND "${contents}" "\n" newline)
        if(newline LESS 0)
            message(FATAL_ERROR "${file} has an incomplete header")
        endif()
        math(EXPR body_start "${newline} + 1")
        string(SUBSTRING "${contents}" ${body_start} -1 contents)
    endforeach()
    # chocmesh.zip was generated by version 0.01. Version 0.03 deliberately
    # renamed otherwise unnamed objects from object_N to chocks_N.
    string(REPLACE "object_" "chocks_" contents "${contents}")
    string(SHA256 hash "${contents}")
    set(${result_name} "${hash}" PARENT_SCOPE)
endfunction()

function(verify_body_checksum file description expected_hash)
    body_hash("${file}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR
            "Checksum mismatch for ${description}:\n"
            "  expected: ${expected_hash}\n"
            "  actual:   ${actual_hash}")
    endif()
    message(STATUS "Verified ${description}")
endfunction()

function(convert_and_verify output expected_hash)
    set(output_file "${OUTPUT_DIR}/${output}.obj")
    message(STATUS "Converting ${output}.obj...")
    execute_process(
        COMMAND "${CHOCTOOBJ}" ${ARGN} "${output_file}"
        RESULT_VARIABLE command_result
        OUTPUT_QUIET
    )
    if(NOT command_result EQUAL 0)
        message(FATAL_ERROR
            "Conversion of ${output}.obj failed with code ${command_result}")
    endif()
    verify_body_checksum("${output_file}" "${output}.obj" "${expected_hash}")
endfunction()

function(expect_failure description expected_error)
    execute_process(
        COMMAND "${CHOCTOOBJ}" ${ARGN}
        RESULT_VARIABLE command_result
        OUTPUT_VARIABLE command_stdout
        ERROR_VARIABLE command_stderr
    )
    if(command_result EQUAL 0)
        message(FATAL_ERROR "${description} unexpectedly succeeded")
    endif()
    if(NOT command_stderr MATCHES "${expected_error}")
        message(FATAL_ERROR
            "Unexpected error for ${description}: '${command_stderr}'")
    endif()
endfunction()

set(PUBLISHED_OPTIONS -thick 4 -flip -negative -clip -human)

if(FORTIFY_FAILURE_TEST)
    # LandEx5 is the smallest nonempty additional model file. Object 109 is
    # the first index entry that refers to additional model data.
    set(reference_file "${OUTPUT_DIR}/fortify-reference.obj")
    set(output_file "${OUTPUT_DIR}/fortify.obj")
    set(fortify_args -raw -extra -offset 0xC478 -index 109
        "${EXTRA_DIR}/LandEx5" "${EXTRA_DIR}/Obj3D5")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env
            CHOC_FORTIFY_FAILURE_SIMULATION=0
            "${CHOCTOOBJ}" ${fortify_args} "${reference_file}"
        RESULT_VARIABLE command_result
        OUTPUT_QUIET
    )
    if(NOT command_result EQUAL 0)
        message(FATAL_ERROR "Fortify reference conversion failed")
    endif()
    body_hash("${reference_file}" expected_hash)
    execute_process(
        COMMAND "${CHOCTOOBJ}" ${fortify_args} "${output_file}"
        RESULT_VARIABLE command_result
        OUTPUT_FILE "${TEST_DIR}/fortify.stdout"
        ERROR_FILE "${TEST_DIR}/fortify.stderr"
    )
    if(NOT command_result EQUAL 0)
        message(FATAL_ERROR
            "Fortify failure simulation failed with code ${command_result}; "
            "see fortify.stdout and fortify.stderr in ${TEST_DIR}")
    endif()
    verify_body_checksum("${output_file}" "Fortify failure simulation output"
        "${expected_hash}")
    return()
endif()

# Published conversions from chocmesh.zip and its taskobey file.
convert_and_verify(chocks
    b01fa588a7cfcf3b2d9971bc56b04ac40ac602ad89ef78e5595592a0fb7b355e
    ${PUBLISHED_OPTIONS} "${LAND}" "${OBJ3D}")
convert_and_verify(extra
    20d86493eb0c30bc200817aedc85603c21f9849d1b97126355899b8fc32c12cd
    ${PUBLISHED_OPTIONS} -extra -raw -last 108
    "${EXTRA_DIR}/Land" "${EXTRA_DIR}/Obj3D0")

set(EXTRA_SUFFIXES 0 1 4 5 E)
set(EXTRA_HASHES
    8ae310d232f422b9f7ecca5f26adbd883a598cc36457f6466abc63ff111f4031
    2155503905838c30789478f159dfbbd5c1650d7b1f5ed65baba4ba84e51b5eac
    43017d3b91c71a2bb65bce21f505d15a57b5546d1f2ea1613c5d85b8dafe1ddf
    f5522ee01ad59bb83d3ba36a8fe023a8557bb60babb9fc284bcf8f1405685959
    eb349f55c73395f4dfb7b470ca20158b1600a93bbb344f3b1ff89024af0c965c)
foreach(index RANGE 0 4)
    list(GET EXTRA_SUFFIXES ${index} suffix)
    list(GET EXTRA_HASHES ${index} hash)
    string(TOLOWER "${suffix}" output_suffix)
    convert_and_verify("extra-${output_suffix}" "${hash}"
        ${PUBLISHED_OPTIONS} -extra -raw -offset 0xC478
        "${EXTRA_DIR}/LandEx${suffix}" "${EXTRA_DIR}/Obj3D${suffix}")
endforeach()

if(DEBUG_OUTPUT)
    message(STATUS "Published conversions passed with debug output")
    return()
endif()

# Alternative input and output syntax.
set(TIGER_OPTIONS -name tiger -human)
set(baseline "${OUTPUT_DIR}/tiger-baseline.obj")
execute_process(COMMAND "${CHOCTOOBJ}" ${TIGER_OPTIONS}
    "${LAND}" "${OBJ3D}" "${baseline}" RESULT_VARIABLE command_result)
if(NOT command_result EQUAL 0)
    message(FATAL_ERROR "Baseline tiger conversion failed")
endif()
body_hash("${baseline}" TIGER_HASH)

set(test_output "${OUTPUT_DIR}/tiger-outfile.obj")
execute_process(COMMAND "${CHOCTOOBJ}" ${TIGER_OPTIONS}
    -outfile "${test_output}" "${LAND}" "${OBJ3D}"
    RESULT_VARIABLE command_result)
if(NOT command_result EQUAL 0)
    message(FATAL_ERROR "-outfile conversion failed")
endif()
verify_body_checksum("${test_output}" "-outfile output" "${TIGER_HASH}")

set(test_output "${OUTPUT_DIR}/tiger-stdin.obj")
execute_process(COMMAND "${CHOCTOOBJ}" ${TIGER_OPTIONS}
    -outfile "${test_output}" "${LAND}"
    INPUT_FILE "${OBJ3D}" RESULT_VARIABLE command_result)
if(NOT command_result EQUAL 0)
    message(FATAL_ERROR "Index input from stdin failed")
endif()
verify_body_checksum("${test_output}" "stdin-index output" "${TIGER_HASH}")

set(test_output "${OUTPUT_DIR}/tiger-stdout.obj")
execute_process(COMMAND "${CHOCTOOBJ}" ${TIGER_OPTIONS}
    "${LAND}" "${OBJ3D}" OUTPUT_FILE "${test_output}"
    RESULT_VARIABLE command_result)
if(NOT command_result EQUAL 0)
    message(FATAL_ERROR "Output to stdout failed")
endif()
verify_body_checksum("${test_output}" "stdout output" "${TIGER_HASH}")

set(test_output "${OUTPUT_DIR}/tiger-stdio.obj")
execute_process(COMMAND "${CHOCTOOBJ}" ${TIGER_OPTIONS} "${LAND}"
    INPUT_FILE "${OBJ3D}" OUTPUT_FILE "${test_output}"
    RESULT_VARIABLE command_result)
if(NOT command_result EQUAL 0)
    message(FATAL_ERROR "stdin/stdout conversion failed")
endif()
verify_body_checksum("${test_output}" "stdin/stdout output" "${TIGER_HASH}")

# Selection, listing, diagnostics, and remaining output options.
foreach(option_set IN ITEMS
        "-index;18"
        "-first;18;-last;18"
        "-false"
        "-simple"
        "-duplicate;-unused"
        "-fans"
        "-strips"
        "-mtllib;alternative.mtl")
    set(test_output "${OUTPUT_DIR}/options.obj")
    execute_process(COMMAND "${CHOCTOOBJ}" ${option_set}
        -outfile "${test_output}" "${LAND}" "${OBJ3D}"
        RESULT_VARIABLE command_result)
    if(NOT command_result EQUAL 0)
        message(FATAL_ERROR "Options '${option_set}' failed")
    endif()
endforeach()

execute_process(COMMAND "${CHOCTOOBJ}" -list -summary -first 18 -last 19
    "${LAND}" "${OBJ3D}" RESULT_VARIABLE command_result
    OUTPUT_VARIABLE command_stdout)
if(NOT command_result EQUAL 0 OR
   NOT command_stdout MATCHES "tiger" OR
   NOT command_stdout MATCHES "Found 20 object addresses")
    message(FATAL_ERROR "List/summary output was unsuccessful or malformed")
endif()

execute_process(COMMAND "${CHOCTOOBJ}" -help RESULT_VARIABLE command_result
    OUTPUT_VARIABLE command_stdout)
if(NOT command_result EQUAL 0 OR NOT command_stdout MATCHES "usage:")
    message(FATAL_ERROR "Help output was unsuccessful or malformed")
endif()

foreach(option IN ITEMS -verbose -debug -time)
    set(test_output "${OUTPUT_DIR}/diagnostic.obj")
    execute_process(COMMAND "${CHOCTOOBJ}" ${option} -name tiger
        -outfile "${test_output}" "${LAND}" "${OBJ3D}"
        RESULT_VARIABLE command_result OUTPUT_VARIABLE command_stdout)
    if(NOT command_result EQUAL 0)
        message(FATAL_ERROR "${option} conversion failed")
    endif()
    if(option STREQUAL "-time" AND
       NOT command_stdout MATCHES "Time taken: [0-9]+\\.[0-9]+ seconds")
        message(FATAL_ERROR "Timer output was malformed")
    endif()
    verify_body_checksum(
        "${test_output}" "abbreviated-switch output" "${TIGER_HASH}")
endforeach()

set(test_output "${OUTPUT_DIR}/abbreviated.obj")
execute_process(COMMAND "${CHOCTOOBJ}" -na tiger -hu -ou "${test_output}"
    "${LAND}" "${OBJ3D}" RESULT_VARIABLE command_result)
if(NOT command_result EQUAL 0)
    message(FATAL_ERROR "Abbreviated switches failed")
endif()
verify_body_checksum(
    "${test_output}" "abbreviated-switch output" "${TIGER_HASH}")

# Invalid command lines.
expect_failure("unknown switch" "Unrecognised switch" -unknown)
expect_failure("missing model file" "Must specify a model data file")
expect_failure("missing output name" "Missing output file name" -outfile)
expect_failure("missing object name" "Missing object name" -name)
expect_failure("missing material library name"
    "Missing materials library file name" -mtllib)
expect_failure("reversed object range"
    "First object number must not exceed last object number" -first 2 -last 1)
expect_failure("fan and strip output together"
    "Cannot split polygons into both triangle fans and strips" -fans -strips)
expect_failure("two output names" "Cannot specify more than one output file"
    -outfile one "${LAND}" "${OBJ3D}" two)
expect_failure("output in list mode"
    "Cannot specify an output file in list or summary mode"
    -list "${LAND}" "${OBJ3D}" unused)
expect_failure("verbose output sent to stdout"
    "Must specify an output file in verbose/timer mode"
    -verbose "${LAND}" "${OBJ3D}")
expect_failure("too many arguments" "Too many arguments"
    "${LAND}" "${OBJ3D}" one two)

message(STATUS "All ChocToObj integration tests passed")
